services:
  efuse-app:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://db/efuse
      REDIS_URI: redis://cache
    depends_on:
      - db
      - cache
    restart: always

  db:
    image: mongo:5

  cache:
    image: redis:6-alpine
