name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14.17"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Unit Test
        run: npm run test:cov

      - name: Archive dist artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: Archive test coverage results
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage
